/**
 * Deterministic mock AskResponse payload matching the exact frozen backend JSON contract from:
 * - backend/app/schemas/ai.py
 * - backend/app/schemas/evidence.py
 * - backend/app/schemas/decision.py
 */
export const MOCK_ASK_RESPONSE = {
  success: true,
  question: "What is our gross revenue by region?",
  answer: "Based on verified database query executions, the North region generated the highest gross revenue at ₹1,200,000, followed by the South region at ₹950,000. North revenue was 26.32% higher than South. Qualitative analysis indicates strong customer acquisition momentum in North.",
  claims: [
    {
      claim_id: "claim_1",
      claim_text: "Database query execution returned observed factual business metrics.",
      evidence_ids: ["ev_fact_1"],
      evidence_type: "FACT",
      is_supported: true
    },
    {
      claim_id: "claim_2",
      claim_text: "Deterministic arithmetic calculation derived from database facts.",
      evidence_ids: ["ev_derived_1"],
      evidence_type: "DERIVED_FACT",
      is_supported: true
    },
    {
      claim_id: "claim_3",
      claim_text: "Qualitative analysis of observed findings: North regional performance suggests higher market demand.",
      evidence_ids: ["ev_inf_1"],
      evidence_type: "INFERENCE",
      is_supported: true
    }
  ],
  evidence: [
    {
      evidence_id: "ev_fact_1",
      evidence_type: "FACT",
      description: "Turn 1 SQL query execution output.",
      source: {
        source_type: "sql_query",
        query_hash: "8f9a2b1c4e7d3f5a6b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a",
        sql: "SELECT c.region, SUM(oi.quantity * oi.unit_price) AS gross_revenue FROM orders o JOIN customers c ON o.customer_id = c.customer_id JOIN order_items oi ON o.order_id = oi.order_id WHERE o.order_status = 'Completed' GROUP BY c.region ORDER BY gross_revenue DESC",
        timestamp: "2026-09-30T00:35:00Z",
        columns: ["region", "gross_revenue"],
        relevant_rows: [
          { region: "North", gross_revenue: 1200000.0 },
          { region: "South", gross_revenue: 950000.0 },
          { region: "East", gross_revenue: 720000.0 },
          { region: "West", gross_revenue: 610000.0 }
        ],
        execution_metadata: {
          execution_time_ms: 14.2,
          row_count: 4,
          truncated: false
        }
      },
      calculation: null,
      limitations: []
    },
    {
      evidence_id: "ev_derived_1",
      evidence_type: "DERIVED_FACT",
      description: "North (1200000.0) is 26.32% higher than South (950000.0).",
      source: null,
      calculation: {
        formula_name: "percentage_change",
        formula: "((North - South) / |South|) * 100",
        inputs: { North: 1200000.0, South: 950000.0 },
        output: 26.32,
        input_evidence_ids: ["ev_fact_1"]
      },
      limitations: []
    },
    {
      evidence_id: "ev_inf_1",
      evidence_type: "INFERENCE",
      description: "Qualitative interpretation derived from database evidence.",
      source: null,
      calculation: null,
      limitations: ["Qualitative interpretation generated by AI engine; requires business domain validation."]
    }
  ],
  analysis: {
    analysis_id: "anal_1",
    summary: "Decision analysis evaluated 1 criteria and produced rankings for 4 candidates with robustness status 'STABLE'.",
    criteria_evaluated: [
      {
        criterion_id: "crit_1",
        criterion_name: "Top Region Value Evaluation",
        metric_name: "gross_revenue",
        operator: ">",
        threshold_value: 0.0,
        actual_value: 1200000.0,
        is_met: true,
        explanation: "Criterion 'Top Region Value Evaluation' was satisfied: gross_revenue actual value (1200000.0) > threshold (0.0)."
      }
    ],
    rankings: [
      { rank: 1, region: "North", gross_revenue: 1200000.0, details: { region: "North", gross_revenue: 1200000.0 } },
      { rank: 2, region: "South", gross_revenue: 950000.0, details: { region: "South", gross_revenue: 950000.0 } },
      { rank: 3, region: "East", gross_revenue: 720000.0, details: { region: "East", gross_revenue: 720000.0 } },
      { rank: 4, region: "West", gross_revenue: 610000.0, details: { region: "West", gross_revenue: 610000.0 } }
    ],
    recommendation: {
      recommendation_id: "rec_1",
      action_title: "Prioritize Region 'North'",
      rationale: "Observed top performance in 'North' with gross_revenue = 1200000.0 based on verified database evidence.",
      supporting_evidence_ids: ["ev_fact_1"],
      relevant_claim_ids: ["claim_1"],
      limitations: [],
      robustness_status: "STABLE"
    },
    robustness: {
      check_id: "rob_1",
      status: "STABLE",
      baseline_scenario: {
        scenario_name: "baseline_completed_orders",
        assumptions: { order_status: "Completed", primary_key: "region" },
        result_summary: { top_candidate: "North", total_rows: 4 },
        is_recommendation_changed: false
      },
      alternate_scenarios: [
        {
          scenario_name: "alternate_margin_sensitivity",
          assumptions: { lead_margin_threshold: "5.0%" },
          result_summary: { lead_margin_percent: 26.32, second_candidate: "South" },
          is_recommendation_changed: false
        }
      ],
      explanation: "Robustness check evaluated lead margin gap (26.32%). Top candidate 'North' lead is strong (>=5%), making finding STABLE.",
      supporting_evidence_ids: ["ev_fact_1"]
    }
  },
  tool_calls: [
    {
      turn: 1,
      tool_name: "sql_query",
      arguments: {
        sql: "SELECT c.region, SUM(oi.quantity * oi.unit_price) AS gross_revenue FROM orders o JOIN customers c ON o.customer_id = c.customer_id JOIN order_items oi ON o.order_id = oi.order_id WHERE o.order_status = 'Completed' GROUP BY c.region ORDER BY gross_revenue DESC",
        max_rows: 50
      },
      result: {
        success: true,
        sql: "SELECT c.region, SUM(oi.quantity * oi.unit_price) AS gross_revenue FROM orders o JOIN customers c ON o.customer_id = c.customer_id JOIN order_items oi ON o.order_id = oi.order_id WHERE o.order_status = 'Completed' GROUP BY c.region ORDER BY gross_revenue DESC",
        data: [
          { region: "North", gross_revenue: 1200000.0 },
          { region: "South", gross_revenue: 950000.0 },
          { region: "East", gross_revenue: 720000.0 },
          { region: "West", gross_revenue: 610000.0 }
        ],
        columns: ["region", "gross_revenue"],
        row_count: 4,
        metadata: {
          execution_time_ms: 14.2,
          row_count: 4,
          columns: ["region", "gross_revenue"],
          truncated: false,
          query_hash: "8f9a2b1c4e7d3f5a6b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a",
          timestamp: "2026-09-30T00:35:00Z"
        },
        error_type: null,
        error_message: null
      }
    }
  ],
  metadata: {
    investigation_id: "inv_mock_123456",
    total_turns: 1,
    max_turns: 3,
    total_tool_calls: 1,
    total_evidence_items: 3,
    total_claims: 3,
    robustness_status: "STABLE"
  },
  error: null
};

export const PRESET_QUESTIONS = [
  "What is our gross revenue by region?",
  "Show top 5 products by total revenue",
  "Compare net revenue and completed order counts across channels",
  "Analyze cancellation and return rates by customer segment"
];

/**
 * Deterministic mock response generator for POST /api/investigations/{id}/reassess
 */
export function getMockReassessResponse(investigationId, scenarioShiftPct = 10.0) {
  const shiftVal = Number(scenarioShiftPct) || 10.0;
  const isSensitive = shiftVal >= 25.0;
  const statusStr = isSensitive ? "SENSITIVE" : "STABLE";

  return {
    investigation_id: investigationId || "inv_mock_123456",
    question: MOCK_ASK_RESPONSE.question,
    original_scenario_shift_pct: 10.0,
    requested_scenario_shift_pct: shiftVal,
    baseline_top_candidate: "North",
    baseline_metric_name: "gross_revenue",
    robustness_check: {
      check_id: `rob_reassess_${Math.round(shiftVal)}`,
      status: statusStr,
      baseline_scenario: {
        scenario_name: "gross_revenue_baseline",
        assumptions: { metric: "gross_revenue", primary_key: "region" },
        result_summary: { top_candidate: "North", top_value: 1200000.0 },
        is_recommendation_changed: false
      },
      alternate_scenarios: [
        {
          scenario_name: `gross_revenue_minus_${Math.round(shiftVal)}_percent`,
          assumptions: { metric: "gross_revenue", shift_pct: -shiftVal },
          result_summary: { top_candidate: isSensitive ? "South" : "North", perturbed_value: Math.round(1200000.0 * (1.0 - shiftVal / 100.0)) },
          is_recommendation_changed: isSensitive
        },
        {
          scenario_name: `gross_revenue_plus_${Math.round(shiftVal)}_percent`,
          assumptions: { metric: "gross_revenue", shift_pct: shiftVal },
          result_summary: { top_candidate: "North", perturbed_value: Math.round(1200000.0 * (1.0 + shiftVal / 100.0)) },
          is_recommendation_changed: false
        }
      ],
      explanation: isSensitive
        ? `Perturbation of ${shiftVal}% reduces top candidate 'North' lead margin below 5.0% threshold against 'South', making finding SENSITIVE.`
        : `Robustness check evaluated automated multi-scenario metric shift (+/-${shiftVal}%). Top candidate 'North' remains STABLE.`,
      supporting_evidence_ids: ["ev_fact_1"]
    },
    reassessed_at: new Date().toISOString()
  };
}

/**
 * Deterministic mock response generator for POST /api/investigations/{id}/review
 */
export function getMockReviewResponse(investigationId, reviewStatus, reviewerId, reviewNotes) {
  return {
    review_id: `rev_mock_${Math.random().toString(36).substring(2, 8)}`,
    investigation_id: investigationId || "inv_mock_123456",
    review_status: reviewStatus || "APPROVED",
    reviewer_id: (reviewerId || "analyst_mock").trim(),
    review_notes: reviewNotes || null,
    reviewed_at: new Date().toISOString()
  };
}

/**
 * Deterministic mock response generator for GET /api/investigations/{id}
 */
export function getMockInvestigationDetail(investigationId) {
  return {
    investigation_id: investigationId || "inv_mock_123456",
    question: MOCK_ASK_RESPONSE.question,
    status: "COMPLETED",
    created_at: "2026-09-30T00:35:00Z",
    completed_at: "2026-09-30T00:35:02Z",
    execution_time_ms: 14.2,
    turns_used: 1,
    tool_calls_count: 1,
    evidence_count: 3,
    claims_count: 3,
    robustness_status: "STABLE",
    result_json: JSON.stringify(MOCK_ASK_RESPONSE),
    error_message: null,
    latest_review: null,
    review_count: 0
  };
}

/**
 * Deterministic mock response generator for GET /api/investigations
 */
export function getMockInvestigationsList(limit = 20, offset = 0) {
  const items = [
    {
      investigation_id: "inv_mock_123456",
      question: "What is our gross revenue by region?",
      status: "COMPLETED",
      created_at: "2026-09-30T00:35:00Z",
      completed_at: "2026-09-30T00:35:02Z",
      execution_time_ms: 14.2,
      turns_used: 1,
      tool_calls_count: 1,
      evidence_count: 3,
      claims_count: 3,
      robustness_status: "STABLE"
    },
    {
      investigation_id: "inv_mock_789012",
      question: "Show top 5 products by total revenue",
      status: "REQUIRES_REVIEW",
      created_at: "2026-09-29T18:20:00Z",
      completed_at: "2026-09-29T18:20:03Z",
      execution_time_ms: 18.5,
      turns_used: 2,
      tool_calls_count: 2,
      evidence_count: 4,
      claims_count: 3,
      robustness_status: "SENSITIVE"
    },
    {
      investigation_id: "inv_mock_345678",
      question: "Compare net revenue and completed order counts across channels",
      status: "COMPLETED",
      created_at: "2026-09-29T14:10:00Z",
      completed_at: "2026-09-29T14:10:01Z",
      execution_time_ms: 12.1,
      turns_used: 1,
      tool_calls_count: 1,
      evidence_count: 2,
      claims_count: 2,
      robustness_status: "STABLE"
    },
    {
      investigation_id: "inv_mock_901234",
      question: "Analyze cancellation and return rates by customer segment",
      status: "FAILED",
      created_at: "2026-09-28T11:05:00Z",
      completed_at: "2026-09-28T11:05:02Z",
      execution_time_ms: 22.0,
      turns_used: 1,
      tool_calls_count: 1,
      evidence_count: 0,
      claims_count: 0,
      robustness_status: "INSUFFICIENT_EVIDENCE"
    }
  ];

  return items.slice(offset, offset + limit);
}

/**
 * Deterministic mock response generator for GET /api/investigations/metrics/summary
 * Matching backend InvestigationMetricsSummary schema.
 */
export function getMockAnalyticsSummary() {
  return {
    total_investigations: 12,
    total_reviews: 5,
    status_counts: {
      COMPLETED: 8,
      REQUIRES_REVIEW: 2,
      FAILED: 1,
      IN_PROGRESS: 1
    },
    review_counts: {
      APPROVED: 3,
      REJECTED: 1,
      FLAGGED: 1
    },
    robustness_counts: {
      STABLE: 7,
      SENSITIVE: 3,
      INSUFFICIENT_EVIDENCE: 1
    },
    average_execution_time_ms: 15.42
  };
}
