/**
 * Deterministic mock AskResponse payload matching the exact frozen backend JSON contract from:
 * - backend/app/schemas/ai.py
 * - backend/app/schemas/evidence.py
 * - backend/app/schemas/decision.py
 */
export const MOCK_ASK_RESPONSE = {
  success: true,
  question: "What is our gross revenue by region?",
  answer: "Based on verified database query executions, the North region generated the highest gross revenue at ₹1,200,000, followed by the South region at ₹950,000. North revenue was 26.32% higher than South. Qualitative analysis indicates strong customer acquisition momentum in North.",
  claims: [
    {
      claim_id: "claim_1",
      claim_text: "Database query execution returned observed factual business metrics.",
      evidence_ids: ["ev_fact_1"],
      evidence_type: "FACT",
      is_supported: true
    },
    {
      claim_id: "claim_2",
      claim_text: "Deterministic arithmetic calculation derived from database facts.",
      evidence_ids: ["ev_derived_1"],
      evidence_type: "DERIVED_FACT",
      is_supported: true
    },
    {
      claim_id: "claim_3",
      claim_text: "Qualitative analysis of observed findings: North regional performance suggests higher market demand.",
      evidence_ids: ["ev_inf_1"],
      evidence_type: "INFERENCE",
      is_supported: true
    }
  ],
  evidence: [
    {
      evidence_id: "ev_fact_1",
      evidence_type: "FACT",
      description: "Turn 1 SQL query execution output.",
      source: {
        source_type: "sql_query",
        query_hash: "8f9a2b1c4e7d3f5a6b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a",
        sql: "SELECT c.region, SUM(oi.quantity * oi.unit_price) AS gross_revenue FROM orders o JOIN customers c ON o.customer_id = c.customer_id JOIN order_items oi ON o.order_id = oi.order_id WHERE o.order_status = 'Completed' GROUP BY c.region ORDER BY gross_revenue DESC",
        timestamp: "2026-09-30T00:35:00Z",
        columns: ["region", "gross_revenue"],
        relevant_rows: [
          { region: "North", gross_revenue: 1200000.0 },
          { region: "South", gross_revenue: 950000.0 },
          { region: "East", gross_revenue: 720000.0 },
          { region: "West", gross_revenue: 610000.0 }
        ],
        execution_metadata: {
          execution_time_ms: 14.2,
          row_count: 4,
          truncated: false
        }
      },
      calculation: null,
      limitations: []
    },
    {
      evidence_id: "ev_derived_1",
      evidence_type: "DERIVED_FACT",
      description: "North (1200000.0) is 26.32% higher than South (950000.0).",
      source: null,
      calculation: {
        formula_name: "percentage_change",
        formula: "((North - South) / |South|) * 100",
        inputs: { North: 1200000.0, South: 950000.0 },
        output: 26.32,
        input_evidence_ids: ["ev_fact_1"]
      },
      limitations: []
    },
    {
      evidence_id: "ev_inf_1",
      evidence_type: "INFERENCE",
      description: "Qualitative interpretation derived from database evidence.",
      source: null,
      calculation: null,
      limitations: ["Qualitative interpretation generated by AI engine; requires business domain validation."]
    }
  ],
  analysis: {
    analysis_id: "anal_1",
    summary: "Decision analysis evaluated 1 criteria and produced rankings for 4 candidates with robustness status 'STABLE'.",
    criteria_evaluated: [
      {
        criterion_id: "crit_1",
        criterion_name: "Top Region Value Evaluation",
        metric_name: "gross_revenue",
        operator: ">",
        threshold_value: 0.0,
        actual_value: 1200000.0,
        is_met: true,
        explanation: "Criterion 'Top Region Value Evaluation' was satisfied: gross_revenue actual value (1200000.0) > threshold (0.0)."
      }
    ],
    rankings: [
      { rank: 1, region: "North", gross_revenue: 1200000.0, details: { region: "North", gross_revenue: 1200000.0 } },
      { rank: 2, region: "South", gross_revenue: 950000.0, details: { region: "South", gross_revenue: 950000.0 } },
      { rank: 3, region: "East", gross_revenue: 720000.0, details: { region: "East", gross_revenue: 720000.0 } },
      { rank: 4, region: "West", gross_revenue: 610000.0, details: { region: "West", gross_revenue: 610000.0 } }
    ],
    recommendation: {
      recommendation_id: "rec_1",
      action_title: "Prioritize Region 'North'",
      rationale: "Observed top performance in 'North' with gross_revenue = 1200000.0 based on verified database evidence.",
      supporting_evidence_ids: ["ev_fact_1"],
      relevant_claim_ids: ["claim_1"],
      limitations: [],
      robustness_status: "STABLE"
    },
    robustness: {
      check_id: "rob_1",
      status: "STABLE",
      baseline_scenario: {
        scenario_name: "baseline_completed_orders",
        assumptions: { order_status: "Completed", primary_key: "region" },
        result_summary: { top_candidate: "North", total_rows: 4 },
        is_recommendation_changed: false
      },
      alternate_scenarios: [
        {
          scenario_name: "alternate_margin_sensitivity",
          assumptions: { lead_margin_threshold: "5.0%" },
          result_summary: { lead_margin_percent: 26.32, second_candidate: "South" },
          is_recommendation_changed: false
        }
      ],
      explanation: "Robustness check evaluated lead margin gap (26.32%). Top candidate 'North' lead is strong (>=5%), making finding STABLE.",
      supporting_evidence_ids: ["ev_fact_1"]
    }
  },
  tool_calls: [
    {
      turn: 1,
      tool_name: "sql_query",
      arguments: {
        sql: "SELECT c.region, SUM(oi.quantity * oi.unit_price) AS gross_revenue FROM orders o JOIN customers c ON o.customer_id = c.customer_id JOIN order_items oi ON o.order_id = oi.order_id WHERE o.order_status = 'Completed' GROUP BY c.region ORDER BY gross_revenue DESC",
        max_rows: 50
      },
      result: {
        success: true,
        sql: "SELECT c.region, SUM(oi.quantity * oi.unit_price) AS gross_revenue FROM orders o JOIN customers c ON o.customer_id = c.customer_id JOIN order_items oi ON o.order_id = oi.order_id WHERE o.order_status = 'Completed' GROUP BY c.region ORDER BY gross_revenue DESC",
        data: [
          { region: "North", gross_revenue: 1200000.0 },
          { region: "South", gross_revenue: 950000.0 },
          { region: "East", gross_revenue: 720000.0 },
          { region: "West", gross_revenue: 610000.0 }
        ],
        columns: ["region", "gross_revenue"],
        row_count: 4,
        metadata: {
          execution_time_ms: 14.2,
          row_count: 4,
          columns: ["region", "gross_revenue"],
          truncated: false,
          query_hash: "8f9a2b1c4e7d3f5a6b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a",
          timestamp: "2026-09-30T00:35:00Z"
        },
        error_type: null,
        error_message: null
      }
    }
  ],
  metadata: {
    total_turns: 1,
    max_turns: 3,
    total_tool_calls: 1,
    total_evidence_items: 3,
    total_claims: 3,
    robustness_status: "STABLE"
  },
  error: null
};

export const PRESET_QUESTIONS = [
  "What is our gross revenue by region?",
  "Show top 5 products by total revenue",
  "Compare net revenue and completed order counts across channels",
  "Analyze cancellation and return rates by customer segment"
];
